//
// Arm.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Arm: Codable, JSONEncodable, Hashable {

    public var interventions: [Intervention]?
    public var name: String?
    public var description: String?
    public var type: String?

    public init(interventions: [Intervention]? = nil, name: String? = nil, description: String? = nil, type: String? = nil) {
        self.interventions = interventions
        self.name = name
        self.description = description
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case interventions
        case name
        case description
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(interventions, forKey: .interventions)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

