//
// AssociatedStudy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AssociatedStudy: Codable, JSONEncodable, Hashable {

    public var studyIdType: String?
    public var studyId: String?

    public init(studyIdType: String? = nil, studyId: String? = nil) {
        self.studyIdType = studyIdType
        self.studyId = studyId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case studyIdType = "study_id_type"
        case studyId = "study_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(studyIdType, forKey: .studyIdType)
        try container.encodeIfPresent(studyId, forKey: .studyId)
    }
}

