//
// Disease.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Disease: Codable, JSONEncodable, Hashable {

    public var inclusionIndicator: String?
    public var isLeadDisease: Bool?
    public var synonyms: [String]?
    public var nciThesaurusConceptId: String?
    public var name: String?
    public var type: [String]?
    public var parents: [String]?

    public init(inclusionIndicator: String? = nil, isLeadDisease: Bool? = nil, synonyms: [String]? = nil, nciThesaurusConceptId: String? = nil, name: String? = nil, type: [String]? = nil, parents: [String]? = nil) {
        self.inclusionIndicator = inclusionIndicator
        self.isLeadDisease = isLeadDisease
        self.synonyms = synonyms
        self.nciThesaurusConceptId = nciThesaurusConceptId
        self.name = name
        self.type = type
        self.parents = parents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inclusionIndicator = "inclusion_indicator"
        case isLeadDisease = "is_lead_disease"
        case synonyms
        case nciThesaurusConceptId = "nci_thesaurus_concept_id"
        case name
        case type
        case parents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inclusionIndicator, forKey: .inclusionIndicator)
        try container.encodeIfPresent(isLeadDisease, forKey: .isLeadDisease)
        try container.encodeIfPresent(synonyms, forKey: .synonyms)
        try container.encodeIfPresent(nciThesaurusConceptId, forKey: .nciThesaurusConceptId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(parents, forKey: .parents)
    }
}

