//
// Eligibility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Eligibility: Codable, JSONEncodable, Hashable {

    public var unstructured: [UnstructuredEligibility]?
    public var structured: StructuredEligibility?

    public init(unstructured: [UnstructuredEligibility]? = nil, structured: StructuredEligibility? = nil) {
        self.unstructured = unstructured
        self.structured = structured
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unstructured
        case structured
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(unstructured, forKey: .unstructured)
        try container.encodeIfPresent(structured, forKey: .structured)
    }
}

