//
// PriorTherapy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PriorTherapy: Codable, JSONEncodable, Hashable {

    public var eligibilityCriterion: String?
    public var inclusionIndicator: String?
    public var synonyms: [String]?
    public var nciThesaurusConceptId: String?
    public var name: String?
    public var ancestorIds: [String]?
    public var parents: [String]?

    public init(eligibilityCriterion: String? = nil, inclusionIndicator: String? = nil, synonyms: [String]? = nil, nciThesaurusConceptId: String? = nil, name: String? = nil, ancestorIds: [String]? = nil, parents: [String]? = nil) {
        self.eligibilityCriterion = eligibilityCriterion
        self.inclusionIndicator = inclusionIndicator
        self.synonyms = synonyms
        self.nciThesaurusConceptId = nciThesaurusConceptId
        self.name = name
        self.ancestorIds = ancestorIds
        self.parents = parents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eligibilityCriterion = "eligibility_criterion"
        case inclusionIndicator = "inclusion_indicator"
        case synonyms
        case nciThesaurusConceptId = "nci_thesaurus_concept_id"
        case name
        case ancestorIds = "ancestor_ids"
        case parents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(eligibilityCriterion, forKey: .eligibilityCriterion)
        try container.encodeIfPresent(inclusionIndicator, forKey: .inclusionIndicator)
        try container.encodeIfPresent(synonyms, forKey: .synonyms)
        try container.encodeIfPresent(nciThesaurusConceptId, forKey: .nciThesaurusConceptId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(ancestorIds, forKey: .ancestorIds)
        try container.encodeIfPresent(parents, forKey: .parents)
    }
}

