//
// StatusHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StatusHistory: Codable, JSONEncodable, Hashable {

    public var statusDate: Date?
    public var status: String?

    public init(statusDate: Date? = nil, status: String? = nil) {
        self.statusDate = statusDate
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case statusDate = "status_date"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(statusDate, forKey: .statusDate)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

