//
// UnstructuredEligibility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UnstructuredEligibility: Codable, JSONEncodable, Hashable {

    public var inclusionIndicator: Bool?
    public var displayOrder: Int?
    public var description: String?

    public init(inclusionIndicator: Bool? = nil, displayOrder: Int? = nil, description: String? = nil) {
        self.inclusionIndicator = inclusionIndicator
        self.displayOrder = displayOrder
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inclusionIndicator = "inclusion_indicator"
        case displayOrder = "display_order"
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inclusionIndicator, forKey: .inclusionIndicator)
        try container.encodeIfPresent(displayOrder, forKey: .displayOrder)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

