//
// InterventionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class InterventionsAPI {

    /**
     Search Interventions by GET
     
     - parameter name: (query) Note that name checks for values assigned to name as well as values assigned to synonyms. (optional)
     - parameter category: (query)  (optional)
     - parameter type: (query)  (optional)
     - parameter codes: (query)  (optional)
     - parameter include: (query) Include only this field(s) in trials and exclude others. Use multiple times to include multiple fields.  (Useful if you want to minimize the payload returned) (optional)
     - parameter sort: (query) Default set to &#39;name&#39;. Currently works only for &lt;code&gt;name&lt;/code&gt; and &lt;code&gt;count&lt;/code&gt;. (optional)
     - parameter order: (query) Asc or Desc. Required when using &lt;code&gt;sort&lt;/code&gt;. (optional)
     - parameter size: (query) Not using the size parameter, by default, will give you ALL the results AND, in addition, will give you the &#39;total&#39; field in the results, with the total count of the results. Once you do use the size parameter however, the number of results will be according to the size specified, AND, in addition, the &#39;total&#39; field will not exist in your results. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func searchInterventionsByGet(name: String? = nil, category: String? = nil, type: String? = nil, codes: String? = nil, include: String? = nil, sort: String? = nil, order: String? = nil, size: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return searchInterventionsByGetWithRequestBuilder(name: name, category: category, type: type, codes: codes, include: include, sort: sort, order: order, size: size).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search Interventions by GET
     - GET /interventions
     - <h3>GET interventions?&lt;filter_params&gt;</h3><p>The <code>interventions</code> endpoint is intended for typeaheads and other use cases where it is necessary to search for available interventions which can later be used to filter clinical trial results. Interventions are matched partially by supplying a string to the <code>name</code> field and may be filtered by other fields through parameters described below. Results are sorted by a combination of in alphabetical order by default i.e sort is set to name and order is set to asc.</p><p>Example <font class='example' color='#0000FF' style='word-wrap: break-word;'>interventions?category=agent%20category&name=Therapeutic</font></p><p><b>Progressive Filtering functionality:</b> All trial fields parameters described at the <b>/trials</b> endpoint are usable here to filter the trials from which you want to aggregate. For example, if you request <b>/interventions?maintype=C4872</b> this will give you all interventions that are in trials where Breast Cancer(C4872) is among the diseases in each trial. Note that <b>maintype</b> is a trials endpoint parameter related to <b>diseases.nci_thesaurus_concept_id</b>.</p><p>When searching  in the interventions Endpoint with multiple values for the following parameters (codes, category, type), API will treat values as an OR condition and will return data that contains one or the other that is being searched.</p><p><b>Examples</b><ul><li><b>codes</b>=C78203&<b>codes</b>=C141136, API will return <b>codes</b> = C78203 <b>OR codes</b> = C141136</li><li><b>category</b>=agent&<b>category</b>=agent%20category&&<b>category</b>=other, API will return <b>category</b> = agent <b>OR category</b> = agent category <b>OR category</b> = other</li><li><b>type</b>=drug&<b>type</b>=genetic, API will return <b>type</b> = drug <b>OR type</b> = genetic </li></ul></p><p><b>codes</b> and <b>code</b> parameters will be used interchangeably within CTS API V2</p><hr>
     - API Key:
       - type: apiKey X-API-KEY (HEADER)
       - name: ApiKeyAuth
     - parameter name: (query) Note that name checks for values assigned to name as well as values assigned to synonyms. (optional)
     - parameter category: (query)  (optional)
     - parameter type: (query)  (optional)
     - parameter codes: (query)  (optional)
     - parameter include: (query) Include only this field(s) in trials and exclude others. Use multiple times to include multiple fields.  (Useful if you want to minimize the payload returned) (optional)
     - parameter sort: (query) Default set to &#39;name&#39;. Currently works only for &lt;code&gt;name&lt;/code&gt; and &lt;code&gt;count&lt;/code&gt;. (optional)
     - parameter order: (query) Asc or Desc. Required when using &lt;code&gt;sort&lt;/code&gt;. (optional)
     - parameter size: (query) Not using the size parameter, by default, will give you ALL the results AND, in addition, will give you the &#39;total&#39; field in the results, with the total count of the results. Once you do use the size parameter however, the number of results will be according to the size specified, AND, in addition, the &#39;total&#39; field will not exist in your results. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func searchInterventionsByGetWithRequestBuilder(name: String? = nil, category: String? = nil, type: String? = nil, codes: String? = nil, include: String? = nil, sort: String? = nil, order: String? = nil, size: Int? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/interventions"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "name": (wrappedValue: name?.encodeToJSON(), isExplode: true),
            "category": (wrappedValue: category?.encodeToJSON(), isExplode: true),
            "type": (wrappedValue: type?.encodeToJSON(), isExplode: true),
            "codes": (wrappedValue: codes?.encodeToJSON(), isExplode: true),
            "include": (wrappedValue: include?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "order": (wrappedValue: order?.encodeToJSON(), isExplode: true),
            "size": (wrappedValue: size?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
